<a href="https://colab.research.google.com/github/tejasvichaturvedi871/799/blob/main/tejasvichaturvedi%2C24570082.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#A create a simple tensor
import tensorflow as tf

x = tf.constant([[10, 20], [30, 40]])
x


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
#Basic tensor operation
a = tf.constant([5, 10])
b = tf.constant([2, 4])

print("Add:", tf.add(a, b))
print("Multiply:", tf.multiply(a, b))
print("Subtract:", tf.subtract(a, b))
print("Divide:", tf.divide(a, b))


Add: tf.Tensor([ 7 14], shape=(2,), dtype=int32)
Multiply: tf.Tensor([10 40], shape=(2,), dtype=int32)
Subtract: tf.Tensor([3 6], shape=(2,), dtype=int32)
Divide: tf.Tensor([2.5 2.5], shape=(2,), dtype=float64)


In [ ]:
#Variable Tensor
v = tf.Variable([1, 2, 3])
print("Before:", v.numpy())

v.assign([4, 5, 6])
print("After:", v.numpy())


Before: [1 2 3]
After: [4 5 6]


In [ ]:
#numpy to tensor
import numpy as np

arr = np.array([[1,2,3]])
tensor = tf.convert_to_tensor(arr)
tensor


<tf.Tensor: shape=(1, 3), dtype=int64, numpy=array([[1, 2, 3]])>

In [ ]:
#Dense layer output
layer = tf.keras.layers.Dense(3, activation="relu")
output = layer(tf.constant([[1., 2., 3.]]))
output


<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1.1909161, 0.       , 2.5331986]], dtype=float32)>

In [ ]:
#Sequential model summary
model = tf.keras.Sequential([
    tf.keras.layers.Dense(5, activation='relu'),
    tf.keras.layers.Dense(1)
])

model.summary()


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
#model compile
model.compile(optimizer="adam", loss="mse", metrics=["mae"])
print("Model Compiled Successfully!")


Model Compiled Successfully!


In [ ]:
#Train on random data
import numpy as np

X = np.random.rand(100, 3)
y = np.random.rand(100, 1)

model.fit(X, y, epochs=5)


Epoch 1/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.3030 - mae: 0.4647 
Epoch 2/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2781 - mae: 0.4442 
Epoch 3/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2565 - mae: 0.4271
Epoch 4/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2435 - mae: 0.4102
Epoch 5/5
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.2290 - mae: 0.3955 


In [ ]:
#Predit
test_data = np.array([[0.3, 0.6, 0.9]])
model.predict(test_data)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step


array([[0.4331265]], dtype=float32)

In [ ]:
#Load MNIST
mnist = tf.keras.datasets.mnist
(X_train, y_train), (X_test, y_test) = mnist.load_data()

print("Training data shape:", X_train.shape)
print("Testing data shape:", X_test.shape)


11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
Training data shape: (60000, 28, 28)
Testing data shape: (10000, 28, 28)
